services:
  onlyoffice:
    container_name: onlyoffice
    image: cmwedding/onlyoffice-licensed
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/var/www/onlyoffice/Data
      - db:/var/lib/postgresql
      - etc:/etc/onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=secret
      - JWT_IN_BODY=true
      - JWT_HEADER=AuthorizationJwt

volumes:
  data:
  db:
  etc:
